logging:
#  config: /Users/jonghunpark/logback.xml
  level:
    root: info #info
    com.simplify: debug #debug

server:
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    driver-class-name: org.h2.Driver
    username: sa
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties.hibernate.hbm2ddl.auto: update
    properties.hibernate.format_sql: true
    showSql: true
    generate-ddl: true

spring:
  url:
    base: http://localhost:8080
  freemarker:
    template-loader-path: "classpath:/templates"