logging:
#  config: /Users/jonghunpark/logback.xml
  level:
    root: debug #info
    com.simplify.api: debug #debug

spring:
  profiles: debug
  h2:
    console:
      enabled: true
  datasource:
    #url: jdbc:h2:tcp://localhost/~/test
    url: jdbc:h2:mem:userdb;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties.hibernate.hbm2ddl.auto: update
    properties.hibernate.format_sql: true
    showSql: true
    generate-ddl: true
  url:
    base: http://localhost:9999