apiVersion: v1
kind: Service
metadata:
  name: njf-app-service
  labels:
    app: njf-app
spec:
  ports:
  - name: web
    port: 8080
    targetPort: 8080
    protocol: TCP
  - name: prom
    port: 9111
    targetPort: 9111
    protocol: TCP
  selector:
    app: njf-app
  type: NodePort
